### ISSUE TITLE
Game freezes when launched until openlauncher is closed

### ISSUE THREAD

**Issue by NSTrains** [IntelOrca/OpenLauncher#10]
OpenLauncher causes OpenLoco to freeze at the last day of the month

**Comment by janisozaur** [comment]
Does that happen when you have autosave turned off? On all scenarios or just some of them? What are the versions of software in question? Where are they placed? What is the operating system version? Why haven't you linked the other bug report?

That's all the info you should've already provided. This is such a low-effort bug report.

**Comment by NSTrains** [comment]
I havent tried with autosave turned off. 
Only one save game that I know has the issue. 
What software are you asking for?
I don't know whatever software your asking and where they placed
Windows 10 21H2

**Comment by karst** [comment]
Also occurs with OpenRCT2, when I close the launcher the game loads just fine.
