### ISSUE TITLE
Latest prerelease does not fetch properly

### ISSUE THREAD

**Issue by beam41** [IntelOrca/OpenLauncher#12]
Currently launcher show latest prerelease at cf6de24 even though we have newer commit on develop.

![image](https://user-images.githubusercontent.com/1791353/192613297-8ab47586-77df-4684-87ac-ce473fbdda29.png)

I figure out what happen. If we use postman to fetch release from github api directly.

```bash
curl --location --request GET 'https://api.github.com/repos/Limetric/OpenRCT2-binaries/releases' \
--header 'Accept: application/vnd.github+json'
```
First tag name will be match with first result in [the release page](https://github.com/Limetric/OpenRCT2-binaries/releases) and so on.

![image](https://user-images.githubusercontent.com/1791353/192613957-e4130ce0-51ce-49b5-ad57-db188c682a83.png)
![image](https://user-images.githubusercontent.com/1791353/192614301-4dbd95f6-af48-4a22-b4d6-b460aba603dc.png)

That mean this api sort by tag name string same as the release page, and that why newer commit on develop doesn't appear because tag start with f come first.

Look at the [documentation](https://docs.github.com/en/rest/releases/releases#list-releases), there is no way we can sort by publish date, but we might be able to fix by expand result to cover all commit in major version. (Which is not really viable)

Graphql version can be sort but need authentication though.

![image](https://user-images.githubusercontent.com/1791353/192615878-f5a15779-6ce8-40b8-b2d9-99a78eb36d4e.png)

**Comment by karst** [comment]
It seems to skip all versions that start with a number.

**Comment by beam41** [comment]
> It seems to skip all versions that start with a number.

Number comes before alphabet (at least in computer) and it sort in descending order. So that's why.

**Comment by beam41** [comment]
> well it's not sorted alphabetically, it's sorted by the release time. In this list at least.

I'm talking about [this list](https://github.com/Limetric/OpenRCT2-binaries/releases) which sort alphabetically and we only get top 50 from them. So that why it miss some recent releases.

**Comment by IntelOrca** [comment]
@beam41 do you know if a GitHub app (no specific repo installation) could be used to authenticate either the REST API or the GraphQL API?

**Comment by beam41** [comment]
> @beam41 do you know if a GitHub app (no specific repo installation) could be used to authenticate either the REST API or the GraphQL API?

GitHub Apps can be use to authenticate both api.
https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api#about-tokens
(This is docs for REST API but GraphQL API works the same)

**Comment by beam41** [comment]
Actually I think you mean "OAuth Apps"

**Comment by IntelOrca** [comment]
@beam41 no, I mean a GitHub App, one that you create on GitHub with a private key and authenticate using a JWT. So the user of the launcher does not need to authenticate, it just uses a shared private/public key for the GitHub App.

I am just wondering whether the GitHub App can use the GraphQL API for finding releases without needing to be enabled/installed for a specific repo - since it is a public repo.

**Comment by beam41** [comment]
https://developer.github.com/changes/2018-04-30-graphql-supports-github-apps/
From this blog it needs user authorisation to do that??
I tries github app token without user behalf and it failed.

**Comment by IntelOrca** [comment]
@beam41 that is a shame. I am not sure how best to resolve this issue without requiring the user to authenticate with a GitHub account. There are over 3,300 releases on the repo and the maximum number of releases you can query is 100, so that is at least 33 / 60 requests to get them all and it takes time to do a query that large.

**Comment by beam41** [comment]
The best I can think is small api server fetch Github releases from Graphql

**Comment by IntelOrca** [comment]
As a temporary measure, `https://api.github.com/repos/limetric/OpenRCT2-binaries/releases/latest` can be used to get the very latest build that was pushed.
